services:
  catalog.db:
    container_name: catalog.db
    image: postgres:latest
    networks: ['catalog_network']
    
  catalog.seq:
    container_name: catalog.seq
    networks: ['catalog_network']
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    networks: ['catalog_network']
          
networks:
  catalog_network:

volumes:
  postgres_catalog:

