services:
  catalog.db:
    container_name: catalog.db
    image: postgres:latest
    networks: ['catalog_network']
    
  catalog.seq:
    container_name: catalog.seq
    networks: ['catalog_network']
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    networks: ['catalog_network']
    
  basket.db:
    container_name: basket.db
    image: postgres:latest
    networks: ['basket_network']
    
  basket.cache:
    container_name: basket.cache
    image: redis:latest
    networks: ['basket_network']

  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    networks: ['basket_network']
          
networks:
  catalog_network:
  basket_network:

volumes:
  postgres_catalog:
  postgres_basket:

