services:
  catalog.db:
    container_name: catalog.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    networks: ['catalog_network']

networks:
  catalog_network:
  

