// <auto-generated />
using System;
using Discount.GRPC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.GRPC.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20250503092519_InitializeDatabase")]
    partial class InitializeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Discount.GRPC.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "IPhone Discount",
                            ProductId = new Guid("019684e3-9bdd-7cf5-812c-3bc984d94b9e"),
                            Rate = 0.29999999999999999
                        },
                        new
                        {
                            Id = 2,
                            Description = "IPhone Discount",
                            ProductId = new Guid("019684e3-9bdd-7cf5-812c-3bc984d94b9e"),
                            Rate = 0.29999999999999999
                        },
                        new
                        {
                            Id = 3,
                            Description = "Samsung Discount",
                            ProductId = new Guid("019684e3-9bdd-747f-a9f6-59f022b24aae"),
                            Rate = 0.10000000000000001
                        },
                        new
                        {
                            Id = 4,
                            Description = "Macbook Discount",
                            ProductId = new Guid("019684e3-9bdd-741e-b3a2-6869f6e0a414"),
                            Rate = 0.10000000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
